apiVersion: auth.okta.upbound.io/v1alpha1
kind: ServerPolicyRule
metadata:
  name: example-policy
spec:
  forProvider:
    authServerIdRef:
      name: auth-server
    policyIdRef:
      name: server-policy
    name: example
    priority: 1
    groupWhitelist:
      - "<group_ids>"
    grantTypeWhitelist:
      - implicit
    scopeWhitelist:
      - "*"