apiVersion: app.okta.upbound.io/v1alpha1
kind: SAMLAppSettings
metadata:
  name: saml-app-settings
spec:
  forProvider:
    appIdRef:
      name: "SAML App Name"
    settings: |
      {
        "appFilter" : "okta",
        "awsEnvironmentType" : "aws.amazon",
        "groupFilter" : "aws_(?{{accountid}}\\\\d+)_(?{{role}}[a-zA-Z0-9+=,.@\\\\-_]+)",
        "joinAllRoles" : false,
        "loginURL" : "https://console.aws.amazon.com/ec2/home",
        "roleValuePattern" : "arn:aws:iam::$${accountid}:saml-provider/OKTA,arn:aws:iam::$${accountid}:role/$${role}",
        "sessionDuration" : 3200,
        "useGroupMapping" : false
      }